package demo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2017-03-06T21:38:58.805-06:00
 * Generated source version: 3.1.3
 * 
 */
@WebService(targetNamespace = "http://demo/", name = "SomeService")
@XmlSeeAlso({ObjectFactory.class})
public interface SomeService {

    @WebMethod
    @RequestWrapper(localName = "someMethod", targetNamespace = "http://demo/", className = "demo.SomeMethod")
    @ResponseWrapper(localName = "someMethodResponse", targetNamespace = "http://demo/", className = "demo.SomeMethodResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean someMethod(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
